"""Generate and validate the ALB bearing configuration reference."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from ALB.api._config_fields import BEARING_FIELD_GROUPS  # noqa: E402
from tools.docs._config_reference import (  # noqa: E402
    contract_digest,
    load_localization,
    render_group,
    validate_groups,
)

SOURCE_PATH = REPOSITORY_ROOT / "docs/api/bearing_config_reference_source.md"
OUTPUT_PATH = REPOSITORY_ROOT / "docs/api/bearing_config_reference.md"

_SIMULATION_SECTION = "\n## `SimulationConfig.loads`\n"


def _narrative() -> str:
    """Return bearing-only Chinese narrative from the maintained source file."""

    content = SOURCE_PATH.read_text(encoding="utf-8")
    if _SIMULATION_SECTION in content:
        content = content.split(_SIMULATION_SECTION, maxsplit=1)[0]
    return content.rstrip()


def build_reference() -> str:
    """Return the complete source-driven UTF-8 bearing reference."""

    validate_groups(BEARING_FIELD_GROUPS)
    localized = load_localization("bearing", BEARING_FIELD_GROUPS)
    lines = [
        _narrative(),
        "",
        "## 源码同步字段合同",
        "",
        "<!-- Generated by tools/docs/generate_bearing_config_reference.py. -->",
        "",
        f"- 配置字段组：`{len(BEARING_FIELD_GROUPS)}`",
        f"- 源码合同摘要：`sha256:{contract_digest(BEARING_FIELD_GROUPS)}`",
        "- 对应规则：字段名、类型、单位、必填性、默认值、可选值、约束、适用范围和原生映射均来自 `ALB.api._config_fields`。",
        "- 阅读方式：上文中文章节解释物理语义和跨字段关系；下表逐项给出可执行源码合同，英文列保留源码原文。",
    ]
    for group_name, fields in BEARING_FIELD_GROUPS.items():
        lines.extend(
            [
                "",
                render_group(group_name, fields, localized[group_name]),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    reference = build_reference()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != reference:
            print(
                "bearing configuration reference is stale; run "
                "tools/docs/generate_bearing_config_reference.py"
            )
            return 1
        print(
            "bearing configuration reference is current: "
            f"{sum(map(len, BEARING_FIELD_GROUPS.values()))} field rows"
        )
        return 0
    OUTPUT_PATH.write_text(reference, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUTPUT_PATH} "
        f"({sum(map(len, BEARING_FIELD_GROUPS.values()))} field rows)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
