"""Generate curated advanced-namespace reference pages for the ALB docs site."""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
METADATA_PATH = REPOSITORY_ROOT / "docs/api/namespace_reference_docs.json"
OUTPUT_ROOT = REPOSITORY_ROOT / "docs/api/namespaces"

_NAMESPACE_SOURCES = {
    "ALB.control": REPOSITORY_ROOT / "ALB/control/__init__.py",
    "ALB.dynamics": REPOSITORY_ROOT / "ALB/dynamics/__init__.py",
    "ALB.surrogate": REPOSITORY_ROOT / "ALB/surrogate/__init__.py",
}


def _exports(path: Path) -> tuple[str, ...]:
    """Read the literal lazy-export registry without importing optional extras."""

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "_EXPORTS"
            for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if not isinstance(value, dict):
                break
            return tuple(str(name) for name in value)
    raise ValueError(f"{path} must define a literal _EXPORTS mapping")


def load_metadata() -> dict[str, Any]:
    """Load and validate namespace documentation metadata."""

    payload = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    if payload.get("schema_version") != "0.4.0":
        raise ValueError("namespace metadata schema_version must be '0.4.0'")
    namespaces = payload.get("namespaces")
    if not isinstance(namespaces, dict) or set(namespaces) != set(_NAMESPACE_SOURCES):
        raise ValueError("namespace metadata must match the curated registry")
    for namespace, source in _NAMESPACE_SOURCES.items():
        entry = namespaces[namespace]
        if not all(entry.get(key) for key in ("title", "extra", "summary")):
            raise ValueError(f"incomplete namespace metadata: {namespace}")
        if entry.get("stability") != "advanced":
            raise ValueError(f"{namespace} must declare advanced stability")
        actual = _exports(source)
        documented = tuple(entry.get("symbols", {}))
        if set(documented) != set(actual):
            raise ValueError(
                f"{namespace} symbols differ from explicit exports; "
                f"documented={sorted(documented)}, actual={sorted(actual)}"
            )
        if any(not entry["symbols"][name] for name in actual):
            raise ValueError(f"{namespace} contains an empty symbol description")
    return payload


def render_namespace(namespace: str, entry: dict[str, Any]) -> str:
    """Render one deterministic Chinese namespace reference page."""

    extra = entry["extra"]
    lines = [
        f"# `.{namespace.split('.')[-1]}` · {entry['title']}",
        "",
        "<!-- Generated by tools/docs/generate_namespace_reference.py. -->",
        "",
        f"> **高级 API。** {entry['summary']}",
        "",
        "## 安装",
        "",
        "```powershell",
        f'E:/Anaconda2023/envs/ALB/python.exe -m pip install "re-alb[{extra}]"',
        "```",
        "",
        "## 导入",
        "",
        "```python",
        f"from {namespace} import {', '.join(entry['symbols'])}",
        "```",
        "",
        "## 显式导出",
        "",
        "| 符号 | 用途 |",
        "| --- | --- |",
    ]
    lines.extend(
        f"| `{name}` | {description} |"
        for name, description in entry["symbols"].items()
    )
    lines.extend(
        [
            "",
            "!!! warning \"高级接口边界\"",
            "    本页只记录 namespace 显式导出的符号。其实现模块、私有 helper 和可导入的内部类型不因此成为稳定用户 API。",
            "",
            "返回[公开接口边界](../../site/concepts/public-api-policy.md)。",
            "",
        ]
    )
    return "\n".join(lines)


def build_references() -> dict[Path, str]:
    """Return every expected generated path and content."""

    metadata = load_metadata()
    return {
        OUTPUT_ROOT / f"{namespace.split('.')[-1]}.md": render_namespace(
            namespace,
            entry,
        )
        for namespace, entry in metadata["namespaces"].items()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = build_references()
    if args.check:
        stale = [
            path
            for path, content in expected.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("stale namespace references: " + ", ".join(map(str, stale)))
            return 1
        print(f"namespace references are current: {len(expected)} pages")
        return 0
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {len(expected)} namespace reference pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
