"""Generate and validate the ALB simulation configuration reference."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from ALB.api._config_fields import SIMULATION_FIELD_GROUPS  # noqa: E402
from tools.docs._config_reference import (  # noqa: E402
    contract_digest,
    load_localization,
    render_group,
    validate_groups,
)

SOURCE_PATH = REPOSITORY_ROOT / "docs/api/simulation_config_reference_source.md"
OUTPUT_PATH = REPOSITORY_ROOT / "docs/api/simulation_config_reference.md"


def build_reference() -> str:
    """Return the complete source-driven UTF-8 simulation reference."""

    validate_groups(SIMULATION_FIELD_GROUPS)
    localized = load_localization("simulation", SIMULATION_FIELD_GROUPS)
    lines = [
        SOURCE_PATH.read_text(encoding="utf-8").rstrip(),
        "",
        "## 完整 JSON5 模板",
        "",
        "```json5",
        "{",
        '  schema_version: "0.4.0",',
        '  kind: "simulation",',
        "  includes: [],",
        "  spec: {",
        "    rotor: {",
        '      model: "ross_excel",',
        '      path: "resources/rotor.xlsx",',
        "      frequency_hz: 50.0,",
        "      alpha: 0.0,",
        "      beta: 0.0,",
        "    },",
        "    time_grid: {time_step: 1e-4, steps: 1000},",
        "    mounts: [",
        '      {bearing: "bearings/left.json5", node: 0},',
        '      {bearing: "bearings/right.json5", node: 4},',
        "    ],",
        "    loads: [",
        '      {type: "gravity", acceleration: 9.80665},',
        '      {type: "static", node: 2, force: [0.0, -100.0]},',
        "    ],",
        "    history: {",
        '      mode: "memory",',
        '      fields: ["rotor_displacement", "rotor_velocity", "bearing_force"],',
        "      downsample: 1,",
        "    },",
        "  },",
        "}",
        "```",
        "",
        "模板中的 Excel 和 bearing 路径是资源占位符，不是 ALB 随包数据。可解析模板位于 `docs/api/examples/templates/simulation_ross_excel.json5`。",
        "",
        "## 源码同步字段合同",
        "",
        "<!-- Generated by tools/docs/generate_simulation_config_reference.py. -->",
        "",
        f"- 配置字段组：`{len(SIMULATION_FIELD_GROUPS)}`",
        f"- 源码合同摘要：`sha256:{contract_digest(SIMULATION_FIELD_GROUPS)}`",
        "- 对应规则：loader 的允许键集合与本页都从 `ALB.api._config_fields` 派生；新增、删除或修改字段会使生成检查失败。",
        "- 英文列保留源码合同，中文标题和摘要来自经过键集合校验的站点语义元数据。",
    ]
    for group_name, fields in SIMULATION_FIELD_GROUPS.items():
        lines.extend(
            [
                "",
                render_group(group_name, fields, localized[group_name]),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    reference = build_reference()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != reference:
            print(
                "simulation configuration reference is stale; run "
                "tools/docs/generate_simulation_config_reference.py"
            )
            return 1
        print(
            "simulation configuration reference is current: "
            f"{sum(map(len, SIMULATION_FIELD_GROUPS.values()))} field rows"
        )
        return 0
    OUTPUT_PATH.write_text(reference, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUTPUT_PATH} "
        f"({sum(map(len, SIMULATION_FIELD_GROUPS.values()))} field rows)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
