[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "re-alb"
version = "0.1.0"
description = "Local package for ALB"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["ALB", "ALB.*"]

[tool.setuptools.package-data]
ALB = ["data/*.json"]
