# coding: utf-8
import control as cl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.linalg
from scipy import signal as ss

from ALB.core.component import BaseSimpleModel
from ALB.infrastructure.persistence import DataFrameResult, SaveTreeNode


def _history_to_frame(history):
    """Convert scalar/vector/matrix history entries into a 2-D DataFrame."""

    rows = []
    for entry in history:
        values = np.asarray(entry)
        if values.ndim == 0:
            rows.append([values.item()])
        else:
            rows.append(values.reshape(-1))
    return pd.DataFrame(rows)


def lti_state_space_matrix_init(a, b, c, d, dt):
    """
    :param a: Continuous-time state matrix A.
    :param b: Continuous-time input matrix B.
    :param c: Continuous-time output matrix C.
    :param d: Continuous-time feedthrough matrix D.

    :return: Discrete equivalent of the continuous state-space matrices.
    """
    lti = ss.lti(a, b, c, d)
    a, b, c, d = lti.A, lti.B, lti.C, lti.D
    A, B, C, D = map(np.asarray, (a, b, c, d))
    n_states = A.shape[0]
    n_inputs = B.shape[1]
    M = np.vstack(
        [
            np.hstack([A * dt, B * dt, np.zeros((n_states, n_inputs))]),
            np.hstack(
                [np.zeros((n_inputs, n_states + n_inputs)), np.identity(n_inputs)]
            ),
            np.zeros((n_inputs, n_states + 2 * n_inputs)),
        ]
    )
    expMT = scipy.linalg.expm(np.transpose(M))
    Ad = expMT[:n_states, :n_states]
    Bd1 = expMT[n_states + n_inputs :, :n_states]
    Bd0 = expMT[n_states : n_states + n_inputs, :n_states] - Bd1
    return Ad, Bd0, Bd1, C, D


def dlti_state_space_matrix_init(a, b, c, d, dt):
    """
    :param a: Continuous-time state matrix A.
    :param b: Continuous-time input matrix B.
    :param c: Continuous-time output matrix C.
    :param d: Continuous-time feedthrough matrix D.

    :return: Discrete state-space matrices generated by scipy.
    """
    lti = ss.lti(a, b, c, d)
    lti = lti.to_discrete(dt)
    return lti.A, lti.B, lti.C, lti.D


class BaseLti(BaseSimpleModel):
    def __init__(self, sys, dt, **kwargs):
        """
        :param sys: Continuous transfer function or state-space model.
        :param dt: Sampling time.

        Optional keyword arguments in kwargs:
        x0 : ndarray, optional, initial system state vector.
        """
        super().__init__()
        # 1. Identify and convert the model to continuous state-space form.
        if isinstance(sys, cl.TransferFunction):
            self.sys_c = cl.tf2ss(sys)
        elif isinstance(sys, cl.StateSpace):
            self.sys_c = sys
        else:
            raise TypeError(
                "sys must be a TransferFunction or StateSpace object from the control package"
            )
        self.sys = self.sys_c
        a, b, c, d = self.sys.A, self.sys.B, self.sys.C, self.sys.D
        mats = self._state_space_matrix_init(a, b, c, d, dt)
        self._set_space_matrix(*mats)
        self._dt = dt
        self.u0 = None
        self.u1 = None
        self.xk0 = kwargs.get("x0", np.zeros(self._a.shape[1]))
        self.xk1 = self.xk0.copy()
        self.ts = []
        self.yout = []
        self.xout = []
        self.u = []

    @property
    def A(self):
        return self.sys.A

    @property
    def B(self):
        return self.sys.B

    @property
    def C(self):
        return self.sys.C

    @property
    def D(self):
        return self.sys.D

    def init(self, *args, **kwargs):
        """
        Initialize internal states and I/O histories.
        """
        self.xk0 = kwargs.get("x0", np.zeros(self._a.shape[1]))
        self.xk1 = self.xk0.copy()
        self.u0 = None
        self.u1 = None
        self.ts = []
        self.yout = []
        self.xout = []
        self.u = []

    def _state_space_matrix_init(self, a, b, c, d, dt):
        return lti_state_space_matrix_init(a, b, c, d, dt)

    def _set_space_matrix(self, *args, **kwargs):
        self._a = args[0]
        self._Bd0 = args[1]
        self._Bd1 = args[2]
        self._c = args[3]
        self._d = args[4]

    def _check_time(self, t, tol=1e-7):
        """
        Check whether the time step matches the configured sampling time.
        tol: Tolerance, default 1e-7.
        """
        if len(self.ts) > 0:
            dt = t - self.ts[-1]
            if np.abs(dt - self._dt) > tol:
                raise ValueError(
                    "Input time interval does not match the system sampling time"
                )

    def _check_input(self, u):
        u = np.array(u)
        u = u.reshape([-1, 1])
        if u.shape[1] != self._Bd1.shape[0]:
            raise Exception("Input vector dimension mismatch")
        return u

    def input(self, t, u, *args, **kwargs):
        # self._check_time(t)
        u = self._check_input(u)
        self.ts.append(t)
        self.u1 = u
        u = np.squeeze(u)
        self.u.append(u)

    def output(self):
        # For the first call, u0 is None and the initial state output is returned.
        if self.u0 is None:
            self.u0 = np.zeros(self._Bd0.shape[0])
            self.xout.append(np.squeeze(self.xk0))
            self.yout.append(np.squeeze(np.dot(self.xk0, np.transpose(self._c))))
            return self.xk0
        # For the second call, if u1 is None, use zero-input by default.
        if self.u1 is None:
            self.u1 = np.zeros(self._Bd1.shape[0])
        self.xk1 = (
            np.dot(self.xk0, self._a)
            + np.dot(self.u0, self._Bd0)
            + np.dot(self.u1, self._Bd1)
        )

        # Save the current input as the previous input for the next step.
        self.u0 = self.u1
        yout = np.squeeze(np.dot(self.xk1, np.transpose(self._c))) + np.squeeze(
            np.dot(self.u1, np.transpose(self._d))
        )
        self.yout.append(np.squeeze(yout))
        self.xk0 = self.xk1
        self.xout.append(np.squeeze(self.xk0))

        return self.yout

    def plot_output(self):
        plt.plot(self.ts, self.yout)
        plt.show()

    def calc_error(self, *args, **kwargs):
        pass

    def save(self, tofile=True, path=None, name=None, *args, **kwargs):
        """
        Save LTI results, including time sequence, input sequence, and output sequence.
        """
        if path is None:
            path = "lti_result"
        if name is None:
            name = "lti"
        t = _history_to_frame(self.ts)
        yout = _history_to_frame(self.yout)
        xout = _history_to_frame(self.xout)
        u = _history_to_frame(self.u)
        res = DataFrameResult(
            {name + "_t": t, name + "_yout": yout, name + "_xout": xout, name + "_u": u}
        )
        node = SaveTreeNode(path, res)
        if tofile:
            node.save_to_file()
        return node


class BaseDlti(BaseLti):
    def __init__(self, sys, dt, **kwargs):
        super().__init__(sys, dt, **kwargs)

    def _state_space_matrix_init(self, a, b, c, d, dt):
        return dlti_state_space_matrix_init(a, b, c, d, dt)

    def _set_space_matrix(self, *args, **kwargs):
        self._a = args[0]
        self._b = args[1]
        self._c = args[2]
        self._d = args[3]

    def _check_input(self, u):
        u = np.array(u)
        u = u.reshape([-1, 1])
        if u.shape[0] != self._b.shape[1]:
            raise Exception("Input vector dimension mismatch")
        return u

    def output(self):
        self.xk1 = np.squeeze(np.dot(self._a, self.xk0)) + np.squeeze(
            np.dot(self._b, self.u1)
        )
        yout = np.dot(self._c, self.xk1) + np.dot(self._d, self.u1)
        self.yout.append(np.squeeze(yout))
        self.xk0 = self.xk1
        self.xout.append(np.squeeze(self.xk0))

        return self.yout


def get_space_matrix_from_sys(system):
    if isinstance(system, ss.TransferFunction):
        system = system.to_ss()
    elif isinstance(system, cl.TransferFunction):
        system = cl.tf2ss(system)
    try:
        a = system.A
        b = system.B
        c = system.C
        d = system.D
    except AttributeError:
        raise Exception("Gs must be a lti syste or tf or ss")
    return a, b, c, d


class TSLti(BaseLti):
    """
    Time-invariant continuous system wrapper.

    Compared with BaseLti, only the input style differs.
    """

    def __init__(self, Gs, dt, **kwargs):
        """
        :param Gs: lti, tf, ss
        :param dt: Sampling time.

        Optional:
        See BaseLti.
        """
        super().__init__(Gs, dt, **kwargs)


class TSDlti(BaseDlti):
    def __init__(self, Gs, dt, **kwargs):
        """
        :param Gs: lti, tf, ss
        :param dt: Sampling time.

        Optional:
        See BaseLti.
        """
        super().__init__(Gs, dt, **kwargs)

