"""Public typed interfaces and DTOs for ALB components."""

from .bearing import (
    BearingCoefficientProtocol,
    BearingProtocol,
    BearingRuntimeProtocol,
    BearingUnitAdapterProtocol,
    DirectSpoolBearingRuntimeProtocol,
    SpoolCommandProviderProtocol,
)
from .block import (
    AdvancingBlock,
    CommandBlock,
    ComputationalBlock,
    EvaluableBlock,
    SolvableBlock,
)
from .control import ControllerProtocol, ServoValveProtocol
from .dynamics import RotorProtocol, RotorStateMap
from .lifecycle import LifecycleState, RuntimeLifecycleProtocol
from .model import (
    ConvergenceStatus,
    TimeGridProtocol,
)
from .notification import NotifierProtocol
from .optional import import_optional_module, missing_optional_dependency
from .observer import (
    ObserverFailure,
    RecordingRecovered,
    StepCompleted,
    StepObserverProtocol,
)
from .ports import (
    BearingInput,
    BearingOutput,
    ControlInput,
    ControlOutput,
    DirectSpoolBearingInput,
    RotorLoadInput,
    RotorState,
    ValveInput,
    ValveOutput,
)
from .results import (
    ArtifactManifest,
    ArtifactRecord,
    ArtifactWriterProtocol,
    ResultBundle,
    ResultSnapshotProtocol,
    result_snapshot,
)
from .recording import (
    DIGEST_ALGORITHM,
    ExpiredRecordKey,
    PendingRecord,
    PendingAwareResultRecorderProtocol,
    RecordConflictError,
    RecordDisposition,
    RecordKey,
    RecordReceipt,
    ResultRecorderProtocol,
    RunCloseStatus,
    RunReceipt,
    StepRecordingStatus,
    UnsupportedResultValueError,
    bundle_digest,
    validate_recordable_bundle,
)
from .result_tree import DataFrameResult, NpyResult, RossRotorResult, SaveTreeNode
from .types import StepContext, UnitSystem

__all__ = [
    "AdvancingBlock",
    "ArtifactManifest",
    "ArtifactRecord",
    "ArtifactWriterProtocol",
    "DataFrameResult",
    "BearingInput",
    "BearingOutput",
    "BearingCoefficientProtocol",
    "BearingProtocol",
    "BearingRuntimeProtocol",
    "BearingUnitAdapterProtocol",
    "CommandBlock",
    "ComputationalBlock",
    "ControlInput",
    "ControlOutput",
    "DirectSpoolBearingInput",
    "DirectSpoolBearingRuntimeProtocol",
    "SpoolCommandProviderProtocol",
    "DIGEST_ALGORITHM",
    "ControllerProtocol",
    "ConvergenceStatus",
    "EvaluableBlock",
    "LifecycleState",
    "NotifierProtocol",
    "ObserverFailure",
    "import_optional_module",
    "missing_optional_dependency",
    "RotorProtocol",
    "RotorStateMap",
    "RotorLoadInput",
    "RotorState",
    "RecordingRecovered",
    "ResultBundle",
    "ResultRecorderProtocol",
    "PendingRecord",
    "PendingAwareResultRecorderProtocol",
    "RecordConflictError",
    "RecordDisposition",
    "RecordKey",
    "RecordReceipt",
    "RunCloseStatus",
    "RunReceipt",
    "StepRecordingStatus",
    "UnsupportedResultValueError",
    "ExpiredRecordKey",
    "bundle_digest",
    "validate_recordable_bundle",
    "ResultSnapshotProtocol",
    "RuntimeLifecycleProtocol",
    "NpyResult",
    "RossRotorResult",
    "SaveTreeNode",
    "ServoValveProtocol",
    "SolvableBlock",
    "StepContext",
    "StepCompleted",
    "StepObserverProtocol",
    "TimeGridProtocol",
    "UnitSystem",
    "ValveInput",
    "ValveOutput",
    "result_snapshot",
]
